export default {
  // settings
  MINIMUM_PLAYERS: 3,
  MAXIMUM_PLAYERS: 8,

  // lobby states
  ADDING_PLAYERS: "ADDING_PLAYERS",
  TUTORIAL_ROUND: "TUTORIAL_ROUND",

  // reducers
  APP_INITIALIZED: "APP_INITIALIZED",
  INIT_GAME: "INIT_GAME",
  ADD_PLAYER: "ADD_PLAYER",
  START_TUTORIAL: "START_TUTORIAL",
  ROUND_ONE: "ROUND_ONE",
};
