export default {
  // settings
  MINIMUM_PLAYERS: 3,
  MAXIMUM_PLAYERS: 8,

  // lobby states
  APP_INITIALIZED: "APP_INITIALIZED",
  INIT_GAME: "INIT_GAME",
  ADDING_PLAYERS: "ADDING_PLAYERS",
  START_TUTORIAL: "START_TUTORIAL",
  ROUND_ONE: "ROUND_ONE",
  ROUND_TWO: "ROUND_TWO",
  FINAL_ROUND: "FINAL_ROUND",

  // reducers
  ADD_AUDIENCE: "ADD_AUDIENCE",
  ANSWER_QUESTIONS: "ANSWER_QUESTIONS",
  PLAYER_VOTING: "PLAYER_VOTING",
  AUDIENCE_VOTING: "AUDIENCE_VOTING",
  UPDATE_SCORES: "UPDATE_SCORES",
  UPDATE_LEADERBOARD: "UPDATE_LEADERBOARD"
};
