export default {
  quetions: [
    "_____: kid tested, mother approved.",
    "What is the next Happy Meal Toy?",
    "What gets better with age?",
    "This is your captain speaking. Fasten your seatbelts and prepare for _____.",
    "I've got 99 problems but _____ ain't one.",
    "What is next in 2020?",
    "What is fun until it gets weird?",
    "The title of the shortest book on earth.",
    "The most expensive software ever imagined.",
    "The most awkward moment in earth's history.",
    "No. NO. NO! I will not let _____ ruin my day.",
    "The real reason that Elon Musk started SpaceX.",
    "The one thing that will prevent us from reaching 2021.",
    "The title of a movie that everyone secretly loves, but will never admit to.",
    "The end of the Silicon Valley will come from _____.",
    "The most annoying thing about Twitter." 
  ],
  comics: [
    "/comics/sleep.png",
    "/comics/hygiene.png",
    "/comics/happiness.png",
    "/comics/year.png",
    "/comics/age.png",
    "/comics/education.png",
    "/comics/elevator.png",
    "/comics/party.png",
  ],
};
